version: "2"

services:
  mongodb_container:
    container_name: mongo
    image: mongo:latest
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  steedos:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: steedos
    ports:
      - 7070:7070
    volumes:
      # - /srv/workflow/cfs:/storage
      # - /srv/git/steedos-contracts-app/src:/app/src
      # - /srv/git/steedos-contracts-app/steedos-config.yml:/app/steedos-config.yml
      # - /srv/git/steedos-contracts-app/.env.local:/app/.env.local


volumes:
  mongodb_data_container: